//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pracownik.cpp
//  @ Date : 17.03.2026
//  @ Author :
//
//


#include "Pracownik.h"
#include <iostream>

Pracownik::Pracownik(std::string i, std::string n) {
    imie = i;
    nazwisko = n;
}

Pracownik::Pracownik() {
    imie = "Brak";
    nazwisko = "Brak";
}

void Pracownik::przedstawSie() {
    std::cout << "- " << imie << " " << nazwisko << std::endl;
}

