//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pracownik.h
//  @ Date : 17.03.2026
//  @ Author :
//
//


#if !defined(_PRACOWNIK_H)
#define _PRACOWNIK_H
#include <string>

class Pracownik {
public:
    Pracownik();
    Pracownik(std::string i, std::string n);
	void przedstawSie();
private:
	std::string imie;
	std::string nazwisko;
	int idPracownika;
	double pensja;
};

#endif  //_PRACOWNIK_H
