//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Programista.cpp
//  @ Date : 17.03.2026
//  @ Author : 
//
//


#include "Programista.h"

void Programista::piszKod() {

}

bool Programista::wykonajCodeReview() {

}

