//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Programista.h
//  @ Date : 17.03.2026
//  @ Author :
//
//


#if !defined(_PROGRAMISTA_H)
#define _PROGRAMISTA_H
#include <string>
#include "Pracownik.h"

class Programista : public Pracownik {
public:
    using Pracownik::Pracownik;
	void piszKod();
	bool wykonajCodeReview();
private:
	std::string jezykProgramowania;
	std::string poziomDoswiadczenia;
};

#endif  //_PROGRAMISTA_H
