//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Zespol.h
//  @ Date : 17.03.2026
//  @ Author :
//
//


#if !defined(_ZESPOL_H)
#define _ZESPOL_H
#include "Programista.h"
#include <string>
#include <vector>

class Zespol {
public:
	void dodajProgramiste(Programista p);
	void wyswietlSklad();
private:
    std::vector<Programista> czlonkowie;
	std::string nazwaZespolu;
	std::string aktualnyProjekt;
};

#endif  //_ZESPOL_H
