//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Zespol.cpp
//  @ Date : 17.03.2026
//  @ Author :
//
//


#include "Zespol.h"
#include "Programista.h"
#include <iostream>

void Zespol::dodajProgramiste(Programista p) {
    czlonkowie.push_back(p);
}

void Zespol::wyswietlSklad() {
    std::cout << "--- Sklad Zespolu ---" << std::endl;
    for(size_t i = 0; i < czlonkowie.size(); i++) {
        czlonkowie[i].przedstawSie();
    }
    std::cout << "---------------------" << std::endl;
}

